### ISSUE TITLE
feature request: naming bundles

### ISSUE THREAD

**Issue by nikki603** [Quramy/angular2-load-children-loader#1]
This is working great for me with Angular2 final and Webpack 2.1.0-beta.22. Thank you!

I'd love the option to name the resulting bundles by the module name instead of 0, 1, 2 ... etc

**Comment by gcphost** [comment]
Ditto, working great but integer chunks are harder to work with then named ones.

**Comment by Quramy** [comment]
Hi. This loader does not affect chunks' name.
Do you want `sub.module.chunk.js`? https://github.com/gdi2290/es6-promise-loader#es6-promise-loader has this options.

> You can optionally specify a name for your chunk after a comma:

For example: 

``` ts
/* src/main/main.routing.ts */
...
    {path: "sub", loadChildren: "es6-promise?,[name]!../sub/sub.module#SubModule" },
...
```

``` js
/* webpack.config.js */
...
  output: {
    path: path.resolve(__dirname, "dist"),
    publicPath: "http://localhost:3000/dist/",
    filename: "[name].js",
    chunkFilename: "[name].chunk.js",
  },
...
```

So you can get `sub.module.chunk.js`.

**Comment by gcphost** [comment]
Seems to work fine with JiT but when I switch to AoT it's back to numbered chunks.

You can see it here:
https://github.com/Askedio/angular2-webpack-aot-treeshake-starter/blob/dev/src/app/app.routing.ts

**Comment by nikki603** [comment]
I have no need for es6-promise-loader.

My routing for angular2 final:

`{ path: '', loadChildren: './dashboard/dashboard.module#DashboardModule' },`

webpack config:

```
output: {
    filename: '[name].bundle.js',
    chunkFilename: '[name].module.js'
  },
```

My lazy loaded modules still have name of 0.bundle.js

**Comment by Sri276286** [comment]
@nikki603 Did you find any solution?

can you please help me. I am also facing same issue.

**Comment by Sri276286** [comment]
@Quramy I tried using the way you told
 But still chunks are being named as 0.bundle.js only .

Any working solution or demo you can share. Please help
